INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_CONTENT_PREVIEW','en','Content Preview');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_CONTENT_PREVIEW','it','Anteprima contenuto');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_BACK_TO_EDIT_CONTENT','en','Back to content editing');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_BACK_TO_EDIT_CONTENT','it','Ritorna in redazione contenuto');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_list','en','list');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_boolean','en','Boolean');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_cbox','en','Checkbox');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_hytext','en','Hypertext');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_threesta','en','Threestate attribute');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_monolist','en','monolist');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_cposite','en','composite');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_ltext','en','Longtext');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_mlist','en','monolist');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_date','en','Exact Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_number','en','Number');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE','en','page');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE','it','pagina');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_MODEL','en','page model');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_MODEL','it','modello pagina');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_TITLE','en','page title');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_TITLE','it','titolo pagina');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_NOT_ALLOWED','en','User not allowed');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_NOT_ALLOWED','it','Utente non autorizzato');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_BASIC','it','Normale');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_BASIC','en','Normal');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_MINT','it','Avanzata');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_MINT','en','Advanced');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_BASIC_GOTO','it','Accedi con client normale');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_BASIC_GOTO','en','Go to the administration with normal client');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_MINT_GOTO','it','Accedi con client avanzato');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ADMINISTRATION_MINT_GOTO','en','Go to the administration with advanced client');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DATE_FROM','en','From');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DATE_FROM','it','Da');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DATE_TO','en','To');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DATE_TO','it','A');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('TEXT','en','Text');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('TEXT','it','Testo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ALL','en','All');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ALL','it','Tutte');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NUMBER_FROM','en','From');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NUMBER_FROM','it','Da');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NUMBER_TO','en','To');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NUMBER_TO','it','A');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCES','it','Risorse API');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCES','en','API Resources');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_ERROR','it','Errore');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_ERROR','en','Errors');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE','it','Risorsa');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE','en','Resource');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_DESCRIPTION','it','Descrizione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_DESCRIPTION','en','Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_DETAILS','it','Vai al dettaglio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_DETAILS','en','Go to details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_OFF','it','Non Attivo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_OFF','en','Not Active');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_FREE','it','Attivo, Accesso Libero');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_FREE','en','Active, Free Access');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_AUTH','it','Attivo, Utenti Registrati');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_AUTH','en','Active, Registered Users');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_LOCK','it','Metodo Attivo, Utenti Registrati con Autorizzazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_LOCK','en','Active, Registered Users with Permission');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_NA','it','Metodo Non Disponibile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_NA','en','Method Not Available');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_NO_RESOURCES','it','Non ci sono Risorse API disponibili.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_NO_RESOURCES','en','No API Resources available at the moment.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_TABLE_SUMMARY','it','La tabella elenaca le Risorse API disponibile nel sistema. Nome della risorsa, la sua descrizione e lo stato di ciascun metodo.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_TABLE_SUMMARY','en','The table lists the API Resources available in the system. Method name, description, group and the status of each method.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAME','it','Nome');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAME','en','Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAMESPACE','it','Namespace');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAMESPACE','en','Namespace');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_SOURCE','it','Sorgente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_SOURCE','en','Source');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_URI','it','URI');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_RESOURCE_URI','en','URI');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_EXTENSION','it','Estensione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_EXTENSION','en','Extension');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_EXTENSION_NOTE','it','''.xml'' per la risposta in formato xml e ''.json'' per la risposta in formato json.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_EXTENSION_NOTE','en','''.xml'' for response in xml format and ''.json'' for json.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_KO','it','Non disponibile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_KO','en','Not available');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD','it','Metodo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD','en','Method');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_OK','it','Disponibile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_OK','en','Available');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTHORIZATION','it','Autorizzazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTHORIZATION','en','Authorization');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_FREE','it','Nessuna, questo metodo � pubblico');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_FREE','en','None, this method is public');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_WITH_PERM','it','Utenti registrati con permesso');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_WITH_PERM','en','Registered users with permission');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_SIMPLE','it','Utenti registrati');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_SIMPLE','en','Registered users');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMAS','it','Schema XML');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMAS','en','XML Schemas');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_REQ','it','Richiesta');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_REQ','en','Request');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_RESP','it','Risposta');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_RESP','en','Response');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_PARAMS_SUMM','it','Questa tabella mostra i parametri per la richiesta del metodo. Per ciascuno di essi ci sono tre colonne: il nome del parametro, la descrizione del parametro e l''indicazione di obbligatoriet�.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_PARAMS_SUMM','en','This table shows the request parameters for this method. For each of them there are three columns: the parameter name, the parameter description and whether if it''s mandatory or not.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_REQUEST_PARAMS','it','Parametri');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_METHOD_REQUEST_PARAMS','en','Parameters');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_NAME','it','Nome');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_NAME','en','Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_DESCRIPTION','it','Descrizione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_DESCRIPTION','en','Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_REQUIRED','it','Obbligatorio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_PARAM_REQUIRED','en','Mandatory');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('YES','it','Si');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('YES','en','Yes');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NO','it','No');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NO','en','No');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_LIST','it','Lista delle Risorse API');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_LIST','en','API Resource List');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ANN_FROM','en','from');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ANN_FROM','it','da');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ANN_TO','en','to');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ANN_TO','it','a');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ANN_DOCUMENTS','en','Documents');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ANN_DOCUMENTS','it','Documenti');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DLD_CATEGORIES','en','Tags');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DLD_CATEGORIES','it','Tag');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_ATTACHMENTS','en','Attachments');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_ATTACHMENTS','it','Allegati');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_LINKS','en','Links');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_LINKS','it','Link');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NWS_ATTACHMENTS','en','Attachments');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NWS_ATTACHMENTS','it','Allegati');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NWS_LINKS','en','Links');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NWS_LINKS','it','Link');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('RSL_DOCUMENTS','en','Documents');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('RSL_DOCUMENTS','it','Documenti');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANGUAGE','en','Language');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANGUAGE','it','Lingua');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANG_it','en','Italiano');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANG_it','it','Italiano');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANG_en','en','English');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLC_LANG_en','it','English');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_WELCOME','en','Hello');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_WELCOME','it','Ciao');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_ADMINISTRATION','en','Administration');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_ADMINISTRATION','it','Amministrazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_SIGNOUT','en','Sign out');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_SIGNOUT','it','Esci');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_SIGNIN','en','Sign in');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_SIGNIN','it','Accedi');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USER_STATUS_EXPIRED','en','Your account has expired!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USER_STATUS_EXPIRED','it','Credenziali scadute!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USER_STATUS_CREDENTIALS_INVALID','en','Wrong username or password!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USER_STATUS_CREDENTIALS_INVALID','it','Le credenziali non sono corrette!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_PROFILE_CONFIGURATION','en','Edit profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_PROFILE_CONFIGURATION','it','Modifica profilo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USERNAME','en','Username');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_USERNAME','it','Utente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_PASSWORD','en','Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESLF_PASSWORD','it','Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESNB_YOU_ARE_HERE','en','You are here');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESNB_YOU_ARE_HERE','it','Sei qui');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESSF_SEARCH','en','Search');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ESSF_SEARCH','it','Cerca');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_DEFAULT_VALUE','it','Default');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_DEFAULT_VALUE','en','Default');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_NAME','it','Nome');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_NAME','en','Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_DESCRIPTION','it','Descrizione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_DESCRIPTION','en','Description');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_REQUIRED','it','Obbligatorio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_REQUIRED','en','Required');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_SCHEMAS','it','XML Schema');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_SCHEMAS','en','XML Schema');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_SCHEMA_RESP','it','Risposta');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_SCHEMA_RESP','en','Response');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS_SUMMARY','it','Summary..');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS_SUMMARY','en','Summary..');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('EDIT_THIS_CONTENT','en','Edit');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('EDIT_THIS_CONTENT','it','Modifica');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PORTAL_TITLE','en','Entando Town');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PORTAL_TITLE','it','Entando Town');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_READ_MORE','en','View details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CNG_READ_MORE','it','Continua');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NWS_READ_MORE','en','View details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('NWS_READ_MORE','it','Continua');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ANN_READ_MORE','en','View details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ANN_READ_MORE','it','Dettagli');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH','en','Search');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH','it','Cerca');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('LIST_VIEWER_EMPTY','en','No result found. Broaden your search and try again!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('LIST_VIEWER_EMPTY','it','Nessun risultato trovato. Imposta dei parametri meno stringenti e prova ancora!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS','en','Search Result');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS','it','Risultati della Ricerca');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCHED_FOR','en','You searched for');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCHED_FOR','it','Hai cercato');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_NOTHING_FOUND','en','No result found. Try another search term!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_NOTHING_FOUND','it','Nessun risultato trovato. Prova a cercare un altro termine!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS_INTRO','en','Found');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS_INTRO','it','Sono stati trovati');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS_OUTRO','en','results. Showing:');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_RESULTS_OUTRO','it','risultati. Mostrati:');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DLD_DOWNLOAD','en','Get it now');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DLD_DOWNLOAD','it','Scarica');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DLD_GET_INFO','en','View details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('DLD_GET_INFO','it','Dettagli');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CARD_HOLDER','en','Holder');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CARD_HOLDER','it','Titolare');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_CARDS','en','Search Cards');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_CARDS','it','Cerca Scheda');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CARDS_NUMBER','en','Number Cards');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CARDS_NUMBER','it','Numero Schede');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('VIEW_CARD','en','Details');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('VIEW_CARD','it','Dettagli');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CARD_NOTE','en','Note');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CARD_NOTE','it','Note');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CARD_DESCRIPTION','en','Area Pass');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CARD_DESCRIPTION','it','Zona Pass');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CARD_CREATION_DATE','en','Release Date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CARD_CREATION_DATE','it','Data Rilascio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('BACK_TO_CARDS_LIST','en','Back to the list');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('BACK_TO_CARDS_LIST','it','Torna alla lista');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('RESERVED_AREA','en','Please sign in');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('RESERVED_AREA','it','? necessario autenticarsi');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USERNAME','en','Username');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USERNAME','it','Utente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PASSWORD','en','Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PASSWORD','it','Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SIGNIN','en','Sign in');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SIGNIN','it','Entra');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('WELCOME','en','Welcome');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('WELCOME','it','Benvenuto');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_CREATION','en','Creation date');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_CREATION','it','Data creazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_ACCESS_LAST','en','Last access');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_ACCESS_LAST','it','Ultimo accesso');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_PASSWORD_CHANGE_LAST','en','Last change');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('USER_DATE_PASSWORD_CHANGE_LAST','it','Ultimo cambio password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('LOGOUT','en','Logout');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('LOGOUT','it','Logout');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_NOT_FOUND','en','Error 404: Page not found.<br />You could try that sporty search form up there in the navigation bar.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGE_NOT_FOUND','it','Error 404: Pagina non trovata.<br />Prova a usare il form di ricerca lass� nella barra di navigazione.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('GENERIC_ERROR','en','500: Generic Error.<br />
This wasn''t supposed to happen. Try again in a few minutes.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('GENERIC_ERROR','it','500: Errore Generico.<br />
Questo non sarebbe dovuto accedere. Prova di nuovo tra qualche minuto.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_SERVICE_LIST','en','Service List');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_GOTO_SERVICE_LIST','it','Elenco Servizi API');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE','en','Service');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE','it','Servizio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_NO_SERVICES','en','No API Services available.<br />The system administrator is able to create new API Services.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_NO_SERVICES','it','Non � disponibile alcun Servizio API.<br />L''amministratore di sistema pu� crearne.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_PREV','en','Previous');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_PREV','it','Indietro');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_NEXT','en','Next');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_NEXT','it','Ancora');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_FIRST','en','Start');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_FIRST','it','Inizio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_LAST','en','End');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_LAST','it','Fine');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_STEP_BACKWARD','en','Previous');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_STEP_BACKWARD','it','Indietro di');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_STEP_FORWARD','en','Next');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('PAGER_STEP_FORWARD','it','Avanti di');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CATEGORY','en','Category');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('CATEGORY','it','Categoria');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('IGNORE','en','Ignore');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('IGNORE','it','Ignora');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('BOTH','en','Both');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('BOTH','it','Entrambi');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_FILTERS_BUTTON','en','Narrow your search');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('SEARCH_FILTERS_BUTTON','it','Filtra ulteriormente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ERRORS','en','Whoops! You''re doing it wrong!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ERRORS','it','Oops! Hai sbagliato qualcosa!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_FIELD','en','The value for field');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_FIELD','it','Il valore del campo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_FORMAT','en','is invalid');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_FORMAT','it','non � corretto');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_RANGE','en','generates an invalid range');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_RANGE','it','genera un range non valido');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('COPYRIGHT','en','Copyright &copy; Entando 2015');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('COPYRIGHT','it','Copyright &copy; Entando 2015');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CONFIGURATION','it','Configura il profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CONFIGURATION','en','Edit profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CONFIRM_NEWPASS','it','Conferma nuova password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CONFIRM_NEWPASS','en','Confirm new password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPASSWORD','it','Modifica Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPASSWORD','en','Edit Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPASSWORD_TITLE','it','Modifica Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPASSWORD_TITLE','en','Edit Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPROFILE_TITLE','it','Modifica profilo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_EDITPROFILE_TITLE','en','Edit Profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEUP','it','Sposta su');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEUP','en','Move up');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEUP_IN','it','Sposta su in posizione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEUP_IN','en','Move at position');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN','it','Sposta giu');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN','en','Move down');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN_IN','it','Sposta giu in posizione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_MOVEDOWN_IN','en','Move down at position');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_REMOVE','it','Rimuovi dalla lista');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ITEM_REMOVE','en','Remove from list');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_MESSAGE_TITLE_FIELDERRORS','it','Attenzione, si sono verificati i seguenti errori nella compilazione del modulo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_MESSAGE_TITLE_FIELDERRORS','en','Warning, please check the module');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_NEWPASS','it','Nuova password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_NEWPASS','en','New password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_OLDPASSWORD','it','Vecchia password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_OLDPASSWORD','en','Old password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PASSWORD_UPDATED','it','La password � stata aggiornata correttamente.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PASSWORD_UPDATED','en','Your password updated successfully.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN','it','E'' necessario effettuare l''accesso');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN','en','Please login');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN_AGAIN','it','E'' necessario riloggarsi.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN_AGAIN','en','Please logout and login again.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN_TO_EDIT_PASSWORD','it','E'' necessario effettuare l''accesso per cambiare la password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PLEASE_LOGIN_TO_EDIT_PASSWORD','en','Please login in order to change your password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PROFILE_UPDATED','it','Profilo aggiornato correttamente.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PROFILE_UPDATED','en','Your profile is now updated.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_SAVE_PASSWORD','it','Salva password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_SAVE_PASSWORD','en','Save password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_SAVE_PROFILE','it','Salva il profilo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_SAVE_PROFILE','en','Save profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ADDITEM_LIST','it','Aggiungi nuovo elemento alla lista');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ADDITEM_LIST','en','Add an element to the list');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_YES','it','Si');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_YES','en','Yes');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_NO','it','No');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_NO','en','No');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_BOTH_YES_AND_NO','it','Indifferente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_BOTH_YES_AND_NO','en','Both');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_SHORT','it','*');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_SHORT','en','*');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_FULL','it','Obbligatorio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MANDATORY_FULL','en','Mandatory');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_SHORT','it','Min');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_SHORT','en','Min');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_FULL','it','Lunghezza Minima');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MINLENGTH_FULL','en','Minimum length');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_SHORT','it','Max');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_SHORT','en','Max');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_FULL','it','Lunghezza Massima');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_ENTITY_ATTRIBUTE_MAXLENGTH_FULL','en','Maximum length');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CURRENT_USER_WITHOUT_PROFILE','it','Utente corrente senza profilo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_CURRENT_USER_WITHOUT_PROFILE','en','Current user without profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_KEY','en','Key');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_KEY','it','Id');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARENT_API','en','Parent API');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARENT_API','it','API Padre');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTHORIZATION','en','Authorization');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTHORIZATION','it','Autorizzazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_FREE','en','Free');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_FREE','it','Accesso Libero');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_URI','en','URI');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_URI','it','URI');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS','en','Parameters');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS','it','Parametri');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_fullname','en','Full Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_email','en','Email');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('userprofile_PFL_enum','en','Enumerator');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpfacetnav_REMOVE_FILTER','it','Rimuovi');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpfacetnav_REMOVE_FILTER','en','Remove');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpfacetnav_TITLE_TREE','it','Albero delle Faccette');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpfacetnav_TITLE_TREE','en','Facet Tree');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpfacetnav_TITLE_FACET_RESULTS','it','Faccette');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpfacetnav_TITLE_FACET_RESULTS','en','Facets');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwidgetutils_ERROR_NO_IFRAME','en','Error - no frame');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwidgetutils_ERROR_NO_IFRAME','it','Errore - no frame');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jprss_FEED_LIST','en','Channels');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jprss_FEED_LIST','it','Canali Rss');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PROFILETYPE','it','Tipo di Profilo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PROFILETYPE','en','Profile Type');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_CHOOSE_TYPE','it','Scegli e continua');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_CHOOSE_TYPE','en','Select and continue');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_SAVE','it','Salva');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_SAVE','en','Save');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_SEND','it','Invia');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_SEND','en','Send');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_SUSPEND','it','Sospendi');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_SUSPEND','en','Suspend');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REQUIRED','it','Obbligatorio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REQUIRED','en','Required');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REQUIRED_FIELD','it','Campo obbligatorio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REQUIRED_FIELD','en','Required field');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REGISTRATION','it','Registrazione Utente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REGISTRATION','en','User Registration');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REGISTRATION_CONFIRM_MSG','it','Registrazione effettuata correttamente.<br/>A breve riceverà una eMail contenente un link di conferma.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REGISTRATION_CONFIRM_MSG','en','User registration successful.<br/>Shortly you''ll receive an eMail with a confirmation link.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ACTIVATION','it','Attivazione Utente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ACTIVATION','en','User Activation');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ACTIVATION_CONFIRM_MSG','it','Attivazione effettuata correttamente.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ACTIVATION_CONFIRM_MSG','en','User activation successful.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ACTIVATION_INFO_MSG','it','Eseguite il login e aggiornate il vostro profilo.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ACTIVATION_INFO_MSG','en','Execute the log-in and update your profile.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PASSWORD_RECOVERY','it','Recupero Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PASSWORD_RECOVERY','en','Password Recovery');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PASSWORD_RECOVER_SUCCESS_MSG','it','Utenza recuperata correttamente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PASSWORD_RECOVER_SUCCESS_MSG','en','Password recovering successful');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_RECOVER_REQUEST_MSG','it','Recupero Utenza');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_RECOVER_REQUEST_MSG','en','User Recovery');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REACTIVATION_PASSWORD_LOST_MSG','it','Recupero Utenza da nome utente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REACTIVATION_PASSWORD_LOST_MSG','en','User Recovery from username');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REACTIVATION_USERNAME_LOST_MSG','it','Recupero Utenza da indirizzo eMail');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REACTIVATION_USERNAME_LOST_MSG','en','User Recovery from eMail address');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ACTIVATION_ERROR_MSG','it','Si è verificato un errore eseguendo l''attivazione dell''utenza. Probabilmente si stà eseguendo l''operazione con dati già utilizzati o fuori tempo massimo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ACTIVATION_ERROR_MSG','en','An error occurred while activating the user. Probably your request is too old and expired.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REACTIVATION_ERROR_MSG','it','Si è verificato un errore eseguendo la riattivazione dell''utenza. Probabilmente si stà eseguendo l''operazione con dati già utilizzati o fuori tempo massimo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REACTIVATION_ERROR_MSG','en','An error occurred while reactivating your account. Probably your request is too old and expired.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_SUSPENDING_CONFIRM_MSG','it','Sospensione Utenza');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_SUSPENDING_CONFIRM_MSG','en','Account Suspension');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_USERNAME','it','Username');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_USERNAME','en','Username');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_NAME','it','Nome');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_NAME','en','Name');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_SURNAME','it','Cognome');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_SURNAME','en','Surname');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_EMAIL','it','eMail');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_EMAIL','en','eMail');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_EMAIL_CONFIRM','it','eMail Confirm');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_EMAIL_CONFIRM','en','eMail confirm');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_LANG','it','Lingua');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_LANG','en','Language');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PASSWORD','it','Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PASSWORD','en','Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PASSWORD_CONFIRM','it','Conferma Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PASSWORD_CONFIRM','en','Password Confirmation');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PRIVACY_AGREEMENT','it','Consenso privacy');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PRIVACY_AGREEMENT','en','Privacy agreement');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ERROR_USER_LOGGED','it','Utente attualmente loggato, non è possibile utilizzare la funzionalità di recupero password. E'' necessario sloggarsi.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ERROR_USER_LOGGED','en','User already logged, you can''t use recover password functionality. You must log out.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ACCOUNT_SUSPENSION','it','Sospensione Account');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ACCOUNT_SUSPENSION','en','Account Suspension');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REGISTRATION_LINK','it','Registrazione');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_REGISTRATION_LINK','en','Registration');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PASSWORD_RECOVER','it','Recupero Password');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PASSWORD_RECOVER','en','Password Recover');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ERROR_USER_ADMIN_OR_NO_ENTANDO_USER','it','Gli amministratori e gli utenti non locali di Entando non possono sospendere il proprio account.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_ERROR_USER_ADMIN_OR_NO_ENTANDO_USER','en','Administrators and the users that aren''t Entando local users can''t suspend their account.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PROFILE_CONFIGURATION','it','Il tuo profilo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpuserreg_PROFILE_CONFIGURATION','en','Your profile');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_CONFIRM_REMOVE','it','Rimuovi');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_LABEL_EMAIL','it','Indirizzo email');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_REGISTER','it','Iscriviti alla newsletter');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_SENT_MAIL','it','Ti è stata inviata una email al tuo indirizzo di posta con il link per confermare la registrazione.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_SUBSCRIPTION_OK','it','La registrazione alla newsletter è avvenuta correttamente. Grazie.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_UNSUB_CONFIRM','it','Confermi la rimozione dalla newsletter?');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_UNSUB_NOMAIL','it','Nessuna email specificata.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_UNSUB_OK','it','Rimozione effettuata correttamente.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_SUBSCRIPTION_NOT_OK','it','Si è verificato un errore in fase di registrazione alla newsletter.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_CONFIRM_REMOVE','en','Remove');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_LABEL_EMAIL','en','Email address');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_REGISTER','en','Subscribe to newsletter');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_SENT_MAIL','en','We sent you an email with a link to confirm your subscription.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_SUBSCRIPTION_OK','en','Newsletter''s subscription successfully happened. Thanks.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_UNSUB_CONFIRM','en','Confirm unsubscription from the newsletter?');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_UNSUB_NOMAIL','en','None specified email.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_UNSUB_OK','en','Unsubscription successfully happened.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpnewsletter_SUBSCRIPTION_NOT_OK','en','An error is happened during newsletter subscription.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_INFO','en','The fields marked with * are required.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_INFO','it','I campi contrassegnati dal simbolo * sono obbligatori.');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MANDATORY_FULL','en','Mandatory');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MANDATORY_FULL','it','Obbligatorio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MANDATORY_SHORT','en','*');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MANDATORY_SHORT','it','*');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MAXLENGTH_FULL','en','Max Length');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MAXLENGTH_FULL','it','Lunghezza massima');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MAXLENGTH_SHORT','en','max');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MAXLENGTH_SHORT','it','max');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MINLENGTH_FULL','en','Min Length');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MINLENGTH_FULL','it','Lunghezza minima');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MINLENGTH_SHORT','en','min');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MINLENGTH_SHORT','it','min');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_INVIA','en','Send');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_INVIA','it','Invia');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_MESSAGE_SAVE_CONFIRMATION','it','Il messaggio è stato inviato correttamente. Se vuoi inviaci un''altra');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_MESSAGE_SAVE_CONFIRMATION','en','The message has been sent successfully. If you need, send us another');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_MESSAGE_REQUEST_LINK','en','request');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_MESSAGE_REQUEST_LINK','it','richiesta');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_SELECT','en','Select');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_SELECT','it','Seleziona');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_MESSAGETYPE','it','Scegliere un tipo di messaggio');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_MESSAGETYPE','en','Choose a message type');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_CHOOSE_TYPE','it','Scegli e continua');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_CHOOSE_TYPE','en','Select and continue');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ERRORS','it','Errori durante la compilazione del modulo');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ERRORS','en','Errors occured');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_YES','it','Si');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_YES','en','Yes');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_NO','it','No');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_NO','en','No');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_NONE','it','Indifferente');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_NONE','en','None');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ERRORS_HAPPENED','it','Si sono verificati degli errori!');
INSERT INTO localstrings (keycode,langcode,stringvalue) VALUES ('jpwebdynamicform_ERRORS_HAPPENED','en','An error has happened!');
