INSERT INTO authpermissions (permissionname,descr) VALUES ('superuser','All functions');
INSERT INTO authpermissions (permissionname,descr) VALUES ('validateContents','Supervision of contents');
INSERT INTO authpermissions (permissionname,descr) VALUES ('manageResources','Operations on Resources');
INSERT INTO authpermissions (permissionname,descr) VALUES ('managePages','Operations on Pages');
INSERT INTO authpermissions (permissionname,descr) VALUES ('enterBackend','Access to Administration Area');
INSERT INTO authpermissions (permissionname,descr) VALUES ('manageCategories','Operations on Categories');
INSERT INTO authpermissions (permissionname,descr) VALUES ('editContents','Content Editing');
INSERT INTO authpermissions (permissionname,descr) VALUES ('jpnewsletter_management','Newsletter management');
INSERT INTO authpermissions (permissionname,descr) VALUES ('jpnewsletter_config','Newsletter Configuration');
INSERT INTO authpermissions (permissionname,descr) VALUES ('jpwebdynamicform_manageForms','Manage Web Dynamic Forms');
